version: '2'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
     - db:db
    ports:
      - "8080:80"

  omeka:
    depends_on:
      - db
    # build: ./
    image: joesong168/omeka-iiif
    # volumes:
      # - ./plugins:/var/www/html/plugins
      # - ./themes:/var/www/html/themes
    ports:
      - "80:80"
    restart: always

